[programs.devnet]
zo_call = "3Bmhmp8CsjiHABUmtTZe8ooNna2MhD37prtg7TwQANZd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/lexingtonbrill/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
